
import {
  FaRocket, FaGraduationCap, FaBriefcase, FaHeartbeat,
  FaTrophy, FaMoneyBillWave, FaPlane, FaMusic,
  FaMicrochip, FaFlask, FaBullhorn, FaHandshake,
  FaBook, FaBaby, FaHome, FaCar, FaGlobe,
  FaRegCalendarCheck, FaStar, FaHeart, FaFlag,
  FaLightbulb, FaBolt, FaTree, FaCamera, FaGamepad,
  FaPalette, FaGift, FaShieldAlt, FaCoffee, FaCode,
  FaChartLine, FaLeaf, FaFire, FaCrown, FaMedal,
  FaTools, FaWrench, FaUtensils, FaDumbbell,
  FaBicycle, FaMotorcycle, FaShip, FaTrain, FaBus,
  FaHospital, FaPills, FaStethoscope, FaMicroscope,
  FaAtom, FaSatellite, FaMoon, FaSun, FaCloud,
  FaSnowflake, FaUmbrella, FaWater, FaDog, FaCat,
  FaFish, FaDragon, FaPaw, FaSeedling, FaMountain,
  FaKey, FaLock, FaEnvelope, FaPhone, FaVideo,
  FaMicrophone, FaHeadphones, FaTv, FaDesktop,
  FaServer, FaDatabase, FaWifi, FaAward, FaRibbon,
  FaPassport, FaWallet, FaCreditCard, FaStore,
  FaWarehouse, FaIndustry, FaHardHat, FaHammer, FaCog,
  FaChartBar, FaChartPie, FaSitemap, FaCodeBranch,
  FaReact, FaNodeJs, FaPython, FaDocker, FaApple,
  FaLinux, FaAndroid, FaRunning, FaHiking,
  FaGolfBall, FaBasketballBall, FaBaseballBall,
  FaTableTennis, FaBowlingBall, FaHockeyPuck, FaFutbol,
  FaGuitar, FaDrum, FaTheaterMasks, FaFilm,
  FaPaintBrush, FaPenFancy, FaRoute, FaUserTie,
  FaUserMd, FaUserGraduate, FaUserNinja, FaUserCog,
  FaPeopleCarry, FaHandsHelping, FaHandHoldingHeart,
  FaDove, FaBirthdayCake, FaGlassCheers, FaWineGlass,
  FaBeer, FaIceCream, FaCookie, FaHamburger,
  FaCompass, FaAnchor, FaLandmark, FaUniversity,
  FaSchool, FaBuilding, FaCity, FaHotel, FaRecycle,
  FaMagic, FaChess, FaPuzzlePiece, FaRobot, FaBrain,
  FaEye, FaSearch, FaFingerprint, FaDna,
  FaGem, FaRing, FaSmile, FaThumbsUp,
  FaBell, FaLink, FaShareAlt, FaQrcode,
  FaFileAlt, FaFilePdf, FaFolderOpen, FaStickyNote,
  FaClipboardCheck, FaTasks, FaCheck,
  FaArrowUp, FaHandHolding, FaMonument,
  FaTachometerAlt, FaSolarPanel, FaBatteryHalf,
  FaCube, FaBoxOpen, FaPaperPlane, FaAt, FaHashtag,
  FaPodcast, FaBroadcastTower, FaNetworkWired,
  FaLocationArrow, FaCrosshairs, FaMapMarkerAlt,
  FaUsers, FaAws, FaSpaceShuttle, FaFeatherAlt,
  FaSnowman, FaLaugh, FaThermometerHalf,
  FaCalendarCheck, FaCalendarPlus,
  FaWeight, FaVial, FaOilCan, FaSkull, FaGhost,
  FaEnvelopeOpen, FaMailBulk, FaBarcode, FaTag,
  FaTicketAlt, FaCouch, FaBed,
  FaMobile, FaTabletAlt, FaKeyboard, FaMouse,
  FaPrint, FaFax, FaProjectDiagram, FaUserAstronaut,
} from "react-icons/fa";

import {
  FaHelicopter,
  FaHatWizard,
  FaMask,
  FaHotdog,
  FaMosque,
  FaSynagogue,
  FaHandHoldingMedical,
  FaFootball,
  FaWandMagicSparkles,
  FaVolleyball,
  FaPersonBiking,
  FaPersonHiking,
  FaPersonSwimming,
  FaPersonRunning,
  FaFaceSmile,
  FaFaceLaughBeam,
  FaFaceSadTear,
  FaFaceAngry,
  FaSailboat,
  FaTemperatureHalf,
  FaDroplet,
  FaFireFlameCurved,
  FaCircleNodes,
  FaBuildingColumns,
  FaClover,
  FaHandsPraying,
  FaBowlFood,
  FaKitMedical,
} from "react-icons/fa6";

const RULES = [
  { keys: ["launch", "deploy", "release"], Icon: FaRocket,         color: "#f97316" },
  { keys: ["graduate", "education", "study"], Icon: FaGraduationCap, color: "#8b5cf6" },
  { keys: ["job", "work", "career"],         Icon: FaBriefcase,     color: "#0ea5e9" },
  { keys: ["health", "hospital", "doctor"],  Icon: FaHeartbeat,     color: "#ef4444" },
  { keys: ["award", "win", "trophy"],        Icon: FaTrophy,        color: "#eab308" },
  { keys: ["money", "revenue", "profit"],    Icon: FaMoneyBillWave, color: "#22c55e" },
  { keys: ["travel", "trip", "visit"],       Icon: FaPlane,         color: "#38bdf8" },
  { keys: ["music", "song", "concert"],      Icon: FaMusic,         color: "#e879f9" },
  { keys: ["code", "software", "ai"],        Icon: FaMicrochip,     color: "#14b8a6" },
];

const DEFAULT = { Icon: FaRegCalendarCheck, color: "#2563eb" };

export const ALL_ICONS = [
  { key: "calendar",    Icon: FaRegCalendarCheck, color: "#2563eb",  label: "Calendar",     group: "General" },
  { key: "star",        Icon: FaStar,             color: "#f59e0b",  label: "Star",         group: "General" },
  { key: "heart",       Icon: FaHeart,            color: "#ef4444",  label: "Heart",        group: "General" },
  { key: "flag",        Icon: FaFlag,             color: "#ef4444",  label: "Flag",         group: "General" },
  { key: "bell",        Icon: FaBell,             color: "#f59e0b",  label: "Bell",         group: "General" },
  { key: "gift",        Icon: FaGift,             color: "#ec4899",  label: "Gift",         group: "General" },
  { key: "trophy",      Icon: FaTrophy,           color: "#eab308",  label: "Trophy",       group: "General" },
  { key: "medal",       Icon: FaMedal,            color: "#f97316",  label: "Medal",        group: "General" },
  { key: "award",       Icon: FaAward,            color: "#eab308",  label: "Award",        group: "General" },
  { key: "crown",       Icon: FaCrown,            color: "#eab308",  label: "Crown",        group: "General" },
  { key: "ribbon",      Icon: FaRibbon,           color: "#ec4899",  label: "Ribbon",       group: "General" },
  { key: "smile",       Icon: FaSmile,            color: "#f59e0b",  label: "Smile",        group: "General" },
  { key: "laugh",       Icon: FaLaugh,            color: "#f59e0b",  label: "Laugh",        group: "General" },
  { key: "thumbsup",    Icon: FaThumbsUp,         color: "#22c55e",  label: "Thumbs Up",    group: "General" },
  { key: "gem",         Icon: FaGem,              color: "#6366f1",  label: "Gem",          group: "General" },
  { key: "ring",        Icon: FaRing,             color: "#f59e0b",  label: "Ring",         group: "General" },
  { key: "magic",       Icon: FaMagic,            color: "#8b5cf6",  label: "Magic",        group: "General" },
  { key: "wand",        Icon: FaWandMagicSparkles,color: "#a78bfa",  label: "Wand",         group: "General" },
  { key: "puzzle",      Icon: FaPuzzlePiece,      color: "#06b6d4",  label: "Puzzle",       group: "General" },
  { key: "chess",       Icon: FaChess,            color: "#64748b",  label: "Chess",        group: "General" },

  { key: "briefcase",   Icon: FaBriefcase,        color: "#0ea5e9",  label: "Work",         group: "Business" },
  { key: "money",       Icon: FaMoneyBillWave,    color: "#22c55e",  label: "Money",        group: "Business" },
  { key: "chartline",   Icon: FaChartLine,        color: "#10b981",  label: "Chart Line",   group: "Business" },
  { key: "chartbar",    Icon: FaChartBar,         color: "#6366f1",  label: "Chart Bar",    group: "Business" },
  { key: "chartpie",    Icon: FaChartPie,         color: "#f97316",  label: "Chart Pie",    group: "Business" },
  { key: "store",       Icon: FaStore,            color: "#0ea5e9",  label: "Store",        group: "Business" },
  { key: "warehouse",   Icon: FaWarehouse,        color: "#64748b",  label: "Warehouse",    group: "Business" },
  { key: "industry",    Icon: FaIndustry,         color: "#475569",  label: "Industry",     group: "Business" },
  { key: "handshake",   Icon: FaHandshake,        color: "#0ea5e9",  label: "Handshake",    group: "Business" },
  { key: "wallet",      Icon: FaWallet,           color: "#22c55e",  label: "Wallet",       group: "Business" },
  { key: "creditcard",  Icon: FaCreditCard,       color: "#6366f1",  label: "Credit Card",  group: "Business" },
  { key: "usertie",     Icon: FaUserTie,          color: "#0ea5e9",  label: "Executive",    group: "Business" },
  { key: "tasks",       Icon: FaTasks,            color: "#14b8a6",  label: "Tasks",        group: "Business" },
  { key: "clipboard",   Icon: FaClipboardCheck,   color: "#22c55e",  label: "Clipboard",    group: "Business" },
  { key: "tachometer",  Icon: FaTachometerAlt,    color: "#f97316",  label: "Dashboard",    group: "Business" },

  { key: "graduation",  Icon: FaGraduationCap,    color: "#8b5cf6",  label: "Education",    group: "Education" },
  { key: "book",        Icon: FaBook,             color: "#0ea5e9",  label: "Book",         group: "Education" },
  { key: "school",      Icon: FaSchool,           color: "#8b5cf6",  label: "School",       group: "Education" },
  { key: "university",  Icon: FaUniversity,       color: "#6366f1",  label: "University",   group: "Education" },
  { key: "usergrad",    Icon: FaUserGraduate,     color: "#8b5cf6",  label: "Graduate",     group: "Education" },
  { key: "penFancy",    Icon: FaPenFancy,         color: "#ec4899",  label: "Writing",      group: "Education" },
  { key: "microscope",  Icon: FaMicroscope,       color: "#14b8a6",  label: "Microscope",   group: "Education" },
  { key: "flask",       Icon: FaFlask,            color: "#a78bfa",  label: "Flask",        group: "Education" },
  { key: "atom",        Icon: FaAtom,             color: "#38bdf8",  label: "Atom",         group: "Education" },
  { key: "dna",         Icon: FaDna,              color: "#22c55e",  label: "DNA",          group: "Education" },
  { key: "brain",       Icon: FaBrain,            color: "#ec4899",  label: "Brain",        group: "Education" },

  { key: "hospital",    Icon: FaHospital,         color: "#ef4444",  label: "Hospital",     group: "Health" },
  { key: "heartbeat",   Icon: FaHeartbeat,        color: "#ef4444",  label: "Heartbeat",    group: "Health" },
  { key: "stethoscope", Icon: FaStethoscope,      color: "#0ea5e9",  label: "Stethoscope",  group: "Health" },
  { key: "pills",       Icon: FaPills,            color: "#8b5cf6",  label: "Pills",        group: "Health" },
  { key: "usermd",      Icon: FaUserMd,           color: "#0ea5e9",  label: "Doctor",       group: "Health" },
  { key: "vial",        Icon: FaVial,             color: "#a78bfa",  label: "Vial",         group: "Health" },
  { key: "kitmedical",  Icon: FaKitMedical,       color: "#ef4444",  label: "First Aid",    group: "Health" },
  { key: "thermometer", Icon: FaThermometerHalf,  color: "#f97316",  label: "Thermometer",  group: "Health" },
  { key: "weight",      Icon: FaWeight,           color: "#64748b",  label: "Weight",       group: "Health" },
  { key: "dumbbell",    Icon: FaDumbbell,         color: "#0ea5e9",  label: "Dumbbell",     group: "Health" },
  { key: "medhand",     Icon: FaHandHoldingMedical,color:"#22c55e",  label: "Med Hand",     group: "Health" },

  { key: "code",        Icon: FaCode,             color: "#14b8a6",  label: "Code",         group: "Tech" },
  { key: "microchip",   Icon: FaMicrochip,        color: "#14b8a6",  label: "Microchip",    group: "Tech" },
  { key: "robot",       Icon: FaRobot,            color: "#6366f1",  label: "Robot",        group: "Tech" },
  { key: "react",       Icon: FaReact,            color: "#38bdf8",  label: "React",        group: "Tech" },
  { key: "nodejs",      Icon: FaNodeJs,           color: "#22c55e",  label: "Node.js",      group: "Tech" },
  { key: "python",      Icon: FaPython,           color: "#eab308",  label: "Python",       group: "Tech" },
  { key: "docker",      Icon: FaDocker,           color: "#38bdf8",  label: "Docker",       group: "Tech" },
  { key: "aws",         Icon: FaAws,              color: "#f97316",  label: "AWS",          group: "Tech" },
  { key: "apple",       Icon: FaApple,            color: "#64748b",  label: "Apple",        group: "Tech" },
  { key: "linux",       Icon: FaLinux,            color: "#eab308",  label: "Linux",        group: "Tech" },
  { key: "android",     Icon: FaAndroid,          color: "#22c55e",  label: "Android",      group: "Tech" },
  { key: "database",    Icon: FaDatabase,         color: "#0ea5e9",  label: "Database",     group: "Tech" },
  { key: "server",      Icon: FaServer,           color: "#6366f1",  label: "Server",       group: "Tech" },
  { key: "wifi",        Icon: FaWifi,             color: "#22c55e",  label: "WiFi",         group: "Tech" },
  { key: "network",     Icon: FaNetworkWired,     color: "#0ea5e9",  label: "Network",      group: "Tech" },
  { key: "satellite",   Icon: FaSatellite,        color: "#6366f1",  label: "Satellite",    group: "Tech" },
  { key: "desktop",     Icon: FaDesktop,          color: "#475569",  label: "Desktop",      group: "Tech" },
  { key: "mobile",      Icon: FaMobile,           color: "#64748b",  label: "Mobile",       group: "Tech" },
  { key: "sitemap",     Icon: FaSitemap,          color: "#8b5cf6",  label: "Sitemap",      group: "Tech" },
  { key: "codebranch",  Icon: FaCodeBranch,       color: "#f97316",  label: "Git Branch",   group: "Tech" },
  { key: "circlenodes", Icon: FaCircleNodes,      color: "#14b8a6",  label: "Nodes",        group: "Tech" },
  { key: "solar",       Icon: FaSolarPanel,       color: "#f59e0b",  label: "Solar",        group: "Tech" },

  { key: "football",    Icon: FaFootball,         color: "#22c55e",  label: "Football",     group: "Sports" },
  { key: "basketball",  Icon: FaBasketballBall,   color: "#f97316",  label: "Basketball",   group: "Sports" },
  { key: "baseball",    Icon: FaBaseballBall,     color: "#ef4444",  label: "Baseball",     group: "Sports" },
  { key: "soccer",      Icon: FaFutbol,           color: "#22c55e",  label: "Soccer",       group: "Sports" },
  { key: "tennis",      Icon: FaTableTennis,      color: "#eab308",  label: "Tennis",       group: "Sports" },
  { key: "golf",        Icon: FaGolfBall,         color: "#f8fafc",  label: "Golf",         group: "Sports" },
  { key: "bowling",     Icon: FaBowlingBall,      color: "#64748b",  label: "Bowling",      group: "Sports" },
  { key: "hockey",      Icon: FaHockeyPuck,       color: "#0ea5e9",  label: "Hockey",       group: "Sports" },

  { key: "plane",       Icon: FaPlane,            color: "#38bdf8",  label: "Flight",       group: "Travel" },
  { key: "car",         Icon: FaCar,              color: "#f97316",  label: "Car",          group: "Travel" },
  { key: "train",       Icon: FaTrain,            color: "#64748b",  label: "Train",        group: "Travel" },
  { key: "ship",        Icon: FaShip,             color: "#0ea5e9",  label: "Ship",         group: "Travel" },
  { key: "bus",         Icon: FaBus,              color: "#eab308",  label: "Bus",          group: "Travel" },
  { key: "motorcycle",  Icon: FaMotorcycle,       color: "#f97316",  label: "Motorcycle",   group: "Travel" },
  { key: "bicycle",     Icon: FaBicycle,          color: "#22c55e",  label: "Bicycle",      group: "Travel" },
  { key: "helicopter",  Icon: FaHelicopter,       color: "#64748b",  label: "Helicopter",   group: "Travel" },
  { key: "sailboat",    Icon: FaSailboat,         color: "#38bdf8",  label: "Sailboat",     group: "Travel" },
  { key: "passport",    Icon: FaPassport,         color: "#2563eb",  label: "Passport",     group: "Travel" },
  { key: "compass",     Icon: FaCompass,          color: "#f97316",  label: "Compass",      group: "Travel" },
  { key: "route",       Icon: FaRoute,            color: "#8b5cf6",  label: "Route",        group: "Travel" },
  { key: "hotel",       Icon: FaHotel,            color: "#0ea5e9",  label: "Hotel",        group: "Travel" },
  { key: "landmark",    Icon: FaLandmark,         color: "#f59e0b",  label: "Landmark",     group: "Travel" },
  { key: "mapmarker",   Icon: FaMapMarkerAlt,     color: "#ef4444",  label: "Map Pin",      group: "Travel" },

  { key: "tree",        Icon: FaTree,             color: "#22c55e",  label: "Tree",         group: "Nature" },
  { key: "fire",        Icon: FaFire,             color: "#ef4444",  label: "Fire",         group: "Nature" },
  { key: "sun",         Icon: FaSun,              color: "#f59e0b",  label: "Sun",          group: "Nature" },
  { key: "moon",        Icon: FaMoon,             color: "#6366f1",  label: "Moon",         group: "Nature" },
  { key: "cloud",       Icon: FaCloud,            color: "#94a3b8",  label: "Cloud",        group: "Nature" },
  { key: "snowflake",   Icon: FaSnowflake,        color: "#38bdf8",  label: "Snowflake",    group: "Nature" },
  { key: "umbrella",    Icon: FaUmbrella,         color: "#6366f1",  label: "Umbrella",     group: "Nature" },
  { key: "water",       Icon: FaWater,            color: "#0ea5e9",  label: "Water",        group: "Nature" },
  { key: "mountain",    Icon: FaMountain,         color: "#64748b",  label: "Mountain",     group: "Nature" },
  { key: "seedling",    Icon: FaSeedling,         color: "#22c55e",  label: "Seedling",     group: "Nature" },
  { key: "leaf",        Icon: FaLeaf,             color: "#22c55e",  label: "Leaf",         group: "Nature" },
  { key: "recycle",     Icon: FaRecycle,          color: "#22c55e",  label: "Recycle",      group: "Nature" },
  { key: "droplet",     Icon: FaDroplet,          color: "#38bdf8",  label: "Droplet",      group: "Nature" },
  { key: "flame",       Icon: FaFireFlameCurved,  color: "#f97316",  label: "Flame",        group: "Nature" },
  { key: "clover",      Icon: FaClover,           color: "#22c55e",  label: "Clover",       group: "Nature" },

  { key: "rocket",       Icon: FaRocket,          color: "#f97316",  label: "Rocket",       group: "Space" },
  { key: "spaceshuttle", Icon: FaSpaceShuttle,    color: "#64748b",  label: "Shuttle",      group: "Space" },
  { key: "astronaut",    Icon: FaUserAstronaut,   color: "#6366f1",  label: "Astronaut",    group: "Space" },

  { key: "dog",         Icon: FaDog,              color: "#a16207",  label: "Dog",          group: "Animals" },
  { key: "cat",         Icon: FaCat,              color: "#6d28d9",  label: "Cat",          group: "Animals" },
  { key: "fish",        Icon: FaFish,             color: "#0ea5e9",  label: "Fish",         group: "Animals" },
  { key: "dragon",      Icon: FaDragon,           color: "#ef4444",  label: "Dragon",       group: "Animals" },
  { key: "paw",         Icon: FaPaw,              color: "#a16207",  label: "Paw",          group: "Animals" },
  { key: "feather",     Icon: FaFeatherAlt,       color: "#94a3b8",  label: "Feather",      group: "Animals" },
  { key: "dove",        Icon: FaDove,             color: "#94a3b8",  label: "Dove",         group: "Animals" },

  { key: "coffee",      Icon: FaCoffee,           color: "#a16207",  label: "Coffee",       group: "Food" },
  { key: "utensils",    Icon: FaUtensils,         color: "#f97316",  label: "Food",         group: "Food" },
  { key: "cake",        Icon: FaBirthdayCake,     color: "#ec4899",  label: "Birthday",     group: "Food" },
  { key: "cheers",      Icon: FaGlassCheers,      color: "#eab308",  label: "Celebration",  group: "Food" },
  { key: "wine",        Icon: FaWineGlass,        color: "#8b5cf6",  label: "Wine",         group: "Food" },
  { key: "beer",        Icon: FaBeer,             color: "#f59e0b",  label: "Beer",         group: "Food" },
  { key: "icecream",    Icon: FaIceCream,         color: "#ec4899",  label: "Ice Cream",    group: "Food" },
  { key: "cookie",      Icon: FaCookie,           color: "#a16207",  label: "Cookie",       group: "Food" },
  { key: "hamburger",   Icon: FaHamburger,        color: "#f97316",  label: "Burger",       group: "Food" },
  { key: "hotdog",      Icon: FaHotdog,           color: "#f97316",  label: "Hot Dog",      group: "Food" },
  { key: "bowlfood",    Icon: FaBowlFood,         color: "#f59e0b",  label: "Bowl",         group: "Food" },

  { key: "music",       Icon: FaMusic,            color: "#e879f9",  label: "Music",        group: "Arts" },
  { key: "guitar",      Icon: FaGuitar,           color: "#a16207",  label: "Guitar",       group: "Arts" },
  { key: "drum",        Icon: FaDrum,             color: "#f97316",  label: "Drum",         group: "Arts" },
  { key: "microphone",  Icon: FaMicrophone,       color: "#ec4899",  label: "Mic",          group: "Arts" },
  { key: "headphones",  Icon: FaHeadphones,       color: "#6366f1",  label: "Headphones",   group: "Arts" },
  { key: "podcast",     Icon: FaPodcast,          color: "#8b5cf6",  label: "Podcast",      group: "Arts" },
  { key: "camera",      Icon: FaCamera,           color: "#8b5cf6",  label: "Camera",       group: "Arts" },
  { key: "film",        Icon: FaFilm,             color: "#f97316",  label: "Film",         group: "Arts" },
  { key: "theater",     Icon: FaTheaterMasks,     color: "#8b5cf6",  label: "Theater",      group: "Arts" },
  { key: "palette",     Icon: FaPalette,          color: "#ec4899",  label: "Palette",      group: "Arts" },
  { key: "paintbrush",  Icon: FaPaintBrush,       color: "#f97316",  label: "Paintbrush",   group: "Arts" },
  { key: "tv",          Icon: FaTv,               color: "#475569",  label: "TV",           group: "Arts" },

  { key: "home",        Icon: FaHome,             color: "#f97316",  label: "Home",         group: "Home" },
  { key: "building",    Icon: FaBuilding,         color: "#64748b",  label: "Building",     group: "Home" },
  { key: "city",        Icon: FaCity,             color: "#475569",  label: "City",         group: "Home" },
  { key: "mosque",      Icon: FaMosque,           color: "#22c55e",  label: "Mosque",       group: "Home" },
  { key: "synagogue",   Icon: FaSynagogue,        color: "#f59e0b",  label: "Synagogue",    group: "Home" },
  { key: "couch",       Icon: FaCouch,            color: "#a16207",  label: "Couch",        group: "Home" },
  { key: "bed",         Icon: FaBed,              color: "#6366f1",  label: "Bed",          group: "Home" },

  { key: "gamepad",     Icon: FaGamepad,          color: "#8b5cf6",  label: "Gaming",       group: "Fun" },
  { key: "ghost",       Icon: FaGhost,            color: "#64748b",  label: "Ghost",        group: "Fun" },
  { key: "skull",       Icon: FaSkull,            color: "#475569",  label: "Skull",        group: "Fun" },
  { key: "snowman",     Icon: FaSnowman,          color: "#38bdf8",  label: "Snowman",      group: "Fun" },
  { key: "wizard",      Icon: FaHatWizard,        color: "#8b5cf6",  label: "Wizard",       group: "Fun" },
  { key: "mask",        Icon: FaMask,             color: "#ec4899",  label: "Mask",         group: "Fun" },
  { key: "ninja",       Icon: FaUserNinja,        color: "#1e293b",  label: "Ninja",        group: "Fun" },
  { key: "fingerprint", Icon: FaFingerprint,      color: "#64748b",  label: "Fingerprint",  group: "Fun" },
  { key: "eye",         Icon: FaEye,              color: "#0ea5e9",  label: "Eye",          group: "Fun" },

  { key: "users",       Icon: FaUsers,            color: "#0ea5e9",  label: "Team",         group: "People" },
  { key: "peoplecarry", Icon: FaPeopleCarry,      color: "#22c55e",  label: "Teamwork",     group: "People" },
  { key: "helping",     Icon: FaHandsHelping,     color: "#22c55e",  label: "Helping",      group: "People" },
  { key: "holdingHeart",Icon: FaHandHoldingHeart, color: "#ef4444",  label: "Care",         group: "People" },
  { key: "usercog",     Icon: FaUserCog,          color: "#6366f1",  label: "User Settings",group: "People" },
  { key: "baby",        Icon: FaBaby,             color: "#ec4899",  label: "Baby",         group: "People" },
  { key: "handspraying",Icon: FaHandsPraying,     color: "#f59e0b",  label: "Praying",      group: "People" },
  { key: "bulldhorn",   Icon: FaBullhorn,         color: "#f97316",  label: "Announce",     group: "People" },

  { key: "key",         Icon: FaKey,              color: "#f59e0b",  label: "Key",          group: "Misc" },
  { key: "lock",        Icon: FaLock,             color: "#ef4444",  label: "Lock",         group: "Misc" },
  { key: "shield",      Icon: FaShieldAlt,        color: "#22c55e",  label: "Shield",       group: "Misc" },
  { key: "tools",       Icon: FaTools,            color: "#f97316",  label: "Tools",        group: "Misc" },
  { key: "wrench",      Icon: FaWrench,           color: "#64748b",  label: "Wrench",       group: "Misc" },
  { key: "hammer",      Icon: FaHammer,           color: "#a16207",  label: "Hammer",       group: "Misc" },
  { key: "hardhat",     Icon: FaHardHat,          color: "#eab308",  label: "Hard Hat",     group: "Misc" },
  { key: "cog",         Icon: FaCog,              color: "#64748b",  label: "Settings",     group: "Misc" },
  { key: "lightbulb",   Icon: FaLightbulb,        color: "#f59e0b",  label: "Idea",         group: "Misc" },
  { key: "bolt",        Icon: FaBolt,             color: "#eab308",  label: "Lightning",    group: "Misc" },
  { key: "anchor",      Icon: FaAnchor,           color: "#0ea5e9",  label: "Anchor",       group: "Misc" },
  { key: "paperplane",  Icon: FaPaperPlane,       color: "#38bdf8",  label: "Send",         group: "Misc" },
  { key: "link",        Icon: FaLink,             color: "#6366f1",  label: "Link",         group: "Misc" },
  { key: "qrcode",      Icon: FaQrcode,           color: "#111827",  label: "QR Code",      group: "Misc" },
  { key: "globe",       Icon: FaGlobe,            color: "#38bdf8",  label: "Globe",        group: "Misc" },
  { key: "monument",    Icon: FaMonument,         color: "#64748b",  label: "Monument",     group: "Misc" },
  { key: "buildingcols",Icon: FaBuildingColumns,  color: "#64748b",  label: "Institution",  group: "Misc" },
  { key: "cube",        Icon: FaCube,             color: "#6366f1",  label: "Cube",         group: "Misc" },
  { key: "broadcast",   Icon: FaBroadcastTower,   color: "#f97316",  label: "Broadcast",    group: "Misc" },
];

const iconOverrides = {};


function resolveKey(eventOrKey) {
  if (typeof eventOrKey === "string") return eventOrKey;
  if (eventOrKey?._eid != null)       return String(eventOrKey._eid);   
  if (eventOrKey?.id  != null)        return String(eventOrKey.id);    
  return `${eventOrKey?.title ?? ""}_${eventOrKey?.date ?? ""}`;       
}

export function setEventIconOverride(eventOrKey, iconKey) {
  const key   = resolveKey(eventOrKey);
  const found = ALL_ICONS.find((i) => i.key === iconKey);
  if (found && key) iconOverrides[key] = { key: found.key, Icon: found.Icon, color: found.color };
}

export function clearEventIconOverride(eventOrKey) {
  delete iconOverrides[resolveKey(eventOrKey)];
}

export function getEventIcon(event) {
  const key = resolveKey(event);
  if (key && iconOverrides[key]) return iconOverrides[key];
  const hay = `${event?.title ?? ""} ${event?.description ?? ""}`.toLowerCase();
  for (const rule of RULES) {
    if (rule.keys.some((k) => hay.includes(k))) return { Icon: rule.Icon, color: rule.color };
  }
  return DEFAULT;
}